// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARJfC5X_25RTZjHZQhOtFThFrrlXqH_f0',
    appId: '1:336568095877:web:a76414047b84f71de8c5ec',
    messagingSenderId: '336568095877',
    projectId: 'vereinsappell',
    authDomain: 'vereinsappell.firebaseapp.com',
    storageBucket: 'vereinsappell.firebasestorage.app',
    measurementId: 'G-53744R6XG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWd1STlPwmn-4mTws3gfMLUgTTPybPcPE',
    appId: '1:336568095877:android:2f2d20d03e846e45e8c5ec',
    messagingSenderId: '336568095877',
    projectId: 'vereinsappell',
    storageBucket: 'vereinsappell.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOqYFf4M7mUYF1pK6C0RGCsaSzIuDDVxo',
    appId: '1:336568095877:ios:6486e04bcd030db7e8c5ec',
    messagingSenderId: '336568095877',
    projectId: 'vereinsappell',
    storageBucket: 'vereinsappell.firebasestorage.app',
    iosBundleId: 'com.example.vereinsAppBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOqYFf4M7mUYF1pK6C0RGCsaSzIuDDVxo',
    appId: '1:336568095877:ios:6486e04bcd030db7e8c5ec',
    messagingSenderId: '336568095877',
    projectId: 'vereinsappell',
    storageBucket: 'vereinsappell.firebasestorage.app',
    iosBundleId: 'com.example.vereinsAppBeta',
  );
}
