#!/bin/bash -e
#
# Updates lib/version.dart with today's date (CalVer: YYYY.MM.DD).
# Run this before each build, or call it from your build pipeline.
#
# Usage:
#   ./build-scripts/bump-version.sh
#   ./build-scripts/bump-version.sh 2026.05.01   # override date

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERSION_FILE="$SCRIPT_DIR/../lib/version.dart"

VERSION="${1:-$(date +%Y.%m.%d.%H%M)}"

cat > "$VERSION_FILE" <<EOF
// Auto-generated by build-scripts/bump-version.sh — do not edit manually.
const String appVersion = '$VERSION';
EOF

echo "✅ Version set to $VERSION"
